#!/bin/bash

echo "🚀 Railway Microservices Deployment Guide"
echo "========================================"
echo ""
echo "Since we can't do interactive Railway commands, follow these steps:"
echo ""

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

echo -e "${YELLOW}1. Gateway Service (Already deploying)${NC}"
echo "   Project URL: https://railway.com/project/e155abc9-0cd8-4c6f-b31d-572fa2548058"
echo "   - Go to the project"
echo "   - Click on the service"
echo "   - Go to Variables tab"
echo "   - Add these variables:"
echo "     AUTH_SERVICE_URL=https://tradesense-auth.up.railway.app"
echo "     TRADING_SERVICE_URL=https://tradesense-trading.up.railway.app"
echo "     ANALYTICS_SERVICE_URL=https://tradesense-analytics.up.railway.app"
echo "     MARKET_DATA_SERVICE_URL=https://tradesense-market-data.up.railway.app"
echo "     BILLING_SERVICE_URL=https://tradesense-billing.up.railway.app"
echo "     AI_SERVICE_URL=https://tradesense-ai.up.railway.app"
echo ""

echo -e "${YELLOW}2. Auth Service${NC}"
echo "   Project URL: https://railway.com/project/c24752c8-ae7a-4577-9579-709ac623bea1"
echo "   - Go to the project"
echo "   - Click 'New' -> 'Database' -> 'Add PostgreSQL'"
echo "   - Then deploy the Auth service:"
echo ""
echo "   cd /home/tarigelamin/Desktop/tradesense/services/auth"
echo "   railway up"
echo ""
echo "   - Add these variables:"
echo "     JWT_SECRET_KEY=your-secret-key-change-in-production"
echo "     DATABASE_URL=(will be auto-set by Railway)"
echo ""

echo -e "${YELLOW}3. Trading Service${NC}"
echo "   cd /home/tarigelamin/Desktop/tradesense/services/trading"
echo "   git init && git add -A && git commit -m 'Initial Trading service'"
echo "   railway init --name tradesense-trading"
echo "   # Add PostgreSQL database in Railway UI"
echo "   railway up"
echo ""
echo "   Variables to add:"
echo "     AUTH_SERVICE_URL=https://tradesense-auth.up.railway.app"
echo "     DATABASE_URL=(will be auto-set by Railway)"
echo ""

echo -e "${GREEN}Quick Commands to Copy:${NC}"
echo ""
echo "# Deploy Auth:"
echo "cd /home/tarigelamin/Desktop/tradesense/services/auth && railway up"
echo ""
echo "# Deploy Trading:"
echo "cd /home/tarigelamin/Desktop/tradesense/services/trading"
echo "git init && git add -A && git commit -m 'Initial Trading service'"
echo "railway init --name tradesense-trading"
echo "railway up"
echo ""

echo -e "${YELLOW}Service URLs (after deployment):${NC}"
echo "Gateway: https://tradesense-gateway.up.railway.app"
echo "Auth: https://tradesense-auth.up.railway.app"
echo "Trading: https://tradesense-trading.up.railway.app"