#!/bin/bash

echo "📋 Railway Logs Helper"
echo "===================="
echo ""
echo "Since Railway CLI doesn't have a direct logs command,"
echo "here are your options to check deployment logs:"
echo ""
echo "1. 🌐 Open Railway Dashboard (Recommended):"
echo "   railway open"
echo "   Then navigate to Deployments → Latest deployment → View logs"
echo ""
echo "2. 🔗 Direct link to your project:"
echo "   https://railway.app/project/08df85d3-c89a-4082-887b-8361569a01f3"
echo ""
echo "3. 🚀 Latest deployment build logs:"
echo "   Check the URL from your last 'railway up' command"
echo ""
echo "4. 💡 Common issues to look for in logs:"
echo "   - ImportError: Check for missing imports"
echo "   - ModuleNotFoundError: Missing dependencies" 
echo "   - ValueError: Environment variable issues"
echo "   - Connection errors: Database connection problems"
echo ""
echo "5. 🔄 To trigger a new deployment:"
echo "   railway up --detach"
echo ""
echo "Press Enter to open Railway dashboard..."
read

railway open 2>/dev/null || echo "Please open: https://railway.app/dashboard"