apiVersion: v1
kind: Secret
metadata:
  name: tradesense-secrets
  namespace: tradesense
type: Opaque
stringData:
  # Database credentials
  DATABASE_URL: "postgresql://tradesense_user:CHANGE_ME@postgres-service:5432/tradesense"
  POSTGRES_PASSWORD: "CHANGE_ME"
  
  # Redis password
  REDIS_PASSWORD: "CHANGE_ME"
  REDIS_URL: "redis://:CHANGE_ME@redis-service:6379/0"
  
  # JWT Secret
  JWT_SECRET_KEY: "CHANGE_ME_TO_RANDOM_64_CHAR_STRING"
  
  # Stripe keys
  STRIPE_API_KEY: "sk_live_CHANGE_ME"
  STRIPE_WEBHOOK_SECRET: "whsec_CHANGE_ME"
  
  # Email configuration
  SMTP_HOST: "smtp.sendgrid.net"
  SMTP_PORT: "587"
  SMTP_USERNAME: "apikey"
  SMTP_PASSWORD: "CHANGE_ME"
  
  # Sentry DSN
  SENTRY_DSN: "https://CHANGE_ME@sentry.io/PROJECT_ID"