apiVersion: v1
kind: Namespace
metadata:
  name: chaos-mesh
  labels:
    name: chaos-mesh
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/warn: privileged
    pod-security.kubernetes.io/audit: privileged