# AWS Secrets Manager SecretStore Configuration
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secrets-manager
  namespace: tradesense
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        # Using IAM roles for service accounts (IRSA) - recommended
        jwt:
          serviceAccountRef:
            name: external-secrets-sa
        # Alternative: Using access key (less secure)
        # secretRef:
        #   accessKeyID:
        #     name: aws-credentials
        #     key: access-key-id
        #   secretAccessKey:
        #     name: aws-credentials
        #     key: secret-access-key
---
# Service Account for IRSA
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-sa
  namespace: tradesense
  annotations:
    # Replace with your actual IAM role ARN
    eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT_ID:role/ExternalSecretsRole
---
# ClusterSecretStore for cross-namespace access
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: aws-secrets-manager-global
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets-sa
            namespace: external-secrets