# External Secrets Operator Installation
# This installs the External Secrets Operator using the official Helm chart values
apiVersion: v1
kind: ConfigMap
metadata:
  name: external-secrets-operator-values
  namespace: external-secrets
data:
  values.yaml: |
    # External Secrets Operator Configuration
    replicaCount: 2
    
    image:
      repository: ghcr.io/external-secrets/external-secrets
      tag: v0.9.11
      pullPolicy: IfNotPresent
    
    # Resource limits for production
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 128Mi
    
    # Enable webhook for validation
    webhook:
      enabled: true
      replicaCount: 2
      resources:
        limits:
          cpu: 200m
          memory: 256Mi
        requests:
          cpu: 50m
          memory: 64Mi
    
    # Enable cert controller
    certController:
      enabled: true
      resources:
        limits:
          cpu: 200m
          memory: 256Mi
        requests:
          cpu: 50m
          memory: 64Mi
    
    # Security context
    securityContext:
      runAsNonRoot: true
      runAsUser: 65534
      fsGroup: 65534
    
    # Pod security context
    podSecurityContext:
      runAsNonRoot: true
      runAsUser: 65534
      fsGroup: 65534
      seccompProfile:
        type: RuntimeDefault
    
    # Service Monitor for Prometheus
    serviceMonitor:
      enabled: true
      namespace: external-secrets
      interval: 30s
      scrapeTimeout: 10s
    
    # Metrics service
    metrics:
      enabled: true
      service:
        port: 8080
    
    # Priority class for critical workloads
    priorityClassName: "system-cluster-critical"
    
    # Pod disruption budget
    podDisruptionBudget:
      enabled: true
      minAvailable: 1
    
    # Node selector for dedicated nodes (optional)
    nodeSelector: {}
    
    # Tolerations for node taints
    tolerations: []
    
    # Anti-affinity for high availability
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                - external-secrets
            topologyKey: kubernetes.io/hostname