# External Secrets for TradeSense Application
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tradesense-backend-secrets
  namespace: tradesense
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: tradesense-secrets
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # Database credentials
        DATABASE_URL: "postgresql://{{ .db_username }}:{{ .db_password }}@{{ .db_host }}:{{ .db_port }}/{{ .db_name }}"
        
        # Redis credentials
        REDIS_URL: "redis://:{{ .redis_password }}@{{ .redis_host }}:{{ .redis_port }}/0"
        
        # Application secrets
        JWT_SECRET_KEY: "{{ .jwt_secret_key }}"
        SECRET_KEY: "{{ .app_secret_key }}"
        MASTER_ENCRYPTION_KEY: "{{ .master_encryption_key }}"
        
        # Third-party services
        STRIPE_API_KEY: "{{ .stripe_api_key }}"
        STRIPE_WEBHOOK_SECRET: "{{ .stripe_webhook_secret }}"
        SENTRY_DSN: "{{ .sentry_dsn }}"
        
        # Email configuration
        SMTP_USERNAME: "{{ .smtp_username }}"
        SMTP_PASSWORD: "{{ .smtp_password }}"
  data:
  # Database secrets
  - secretKey: db_username
    remoteRef:
      key: tradesense/production/database
      property: username
  - secretKey: db_password
    remoteRef:
      key: tradesense/production/database
      property: password
  - secretKey: db_host
    remoteRef:
      key: tradesense/production/database
      property: host
  - secretKey: db_port
    remoteRef:
      key: tradesense/production/database
      property: port
  - secretKey: db_name
    remoteRef:
      key: tradesense/production/database
      property: database
  
  # Redis secrets
  - secretKey: redis_password
    remoteRef:
      key: tradesense/production/redis
      property: password
  - secretKey: redis_host
    remoteRef:
      key: tradesense/production/redis
      property: host
  - secretKey: redis_port
    remoteRef:
      key: tradesense/production/redis
      property: port
  
  # Application secrets
  - secretKey: jwt_secret_key
    remoteRef:
      key: tradesense/production/app
      property: jwt_secret_key
  - secretKey: app_secret_key
    remoteRef:
      key: tradesense/production/app
      property: secret_key
  - secretKey: master_encryption_key
    remoteRef:
      key: tradesense/production/app
      property: master_encryption_key
  
  # Stripe secrets
  - secretKey: stripe_api_key
    remoteRef:
      key: tradesense/production/stripe
      property: api_key
  - secretKey: stripe_webhook_secret
    remoteRef:
      key: tradesense/production/stripe
      property: webhook_secret
  
  # Monitoring secrets
  - secretKey: sentry_dsn
    remoteRef:
      key: tradesense/production/monitoring
      property: sentry_dsn
  
  # Email secrets
  - secretKey: smtp_username
    remoteRef:
      key: tradesense/production/email
      property: username
  - secretKey: smtp_password
    remoteRef:
      key: tradesense/production/email
      property: password
---
# External Secret for staging environment
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tradesense-backend-secrets-staging
  namespace: tradesense-staging
spec:
  refreshInterval: 15m
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: tradesense-secrets
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: tradesense/staging/all-secrets
---
# External Secret for TLS certificates
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tradesense-tls-cert
  namespace: tradesense
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: tradesense-tls
    creationPolicy: Owner
    template:
      type: kubernetes.io/tls
      data:
        tls.crt: "{{ .tls_cert | b64dec }}"
        tls.key: "{{ .tls_key | b64dec }}"
  data:
  - secretKey: tls_cert
    remoteRef:
      key: tradesense/production/tls
      property: certificate
  - secretKey: tls_key
    remoteRef:
      key: tradesense/production/tls
      property: private_key