# HashiCorp Vault SecretStore Configuration (Alternative to AWS)
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-secrets
  namespace: tradesense
spec:
  provider:
    vault:
      server: "https://vault.tradesense.com:8200"
      path: "secret"
      version: "v2"
      auth:
        # Kubernetes auth method
        kubernetes:
          mountPath: "kubernetes"
          role: "external-secrets"
          serviceAccountRef:
            name: external-secrets-sa
        # Alternative: AppRole auth
        # appRole:
        #   path: "approle"
        #   roleId: "role-id"
        #   secretRef:
        #     name: vault-approle
        #     key: secret-id
      # TLS configuration
      caBundle: |
        -----BEGIN CERTIFICATE-----
        # Your Vault CA certificate here
        -----END CERTIFICATE-----
---
# Vault policy for External Secrets
apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-policy
  namespace: external-secrets
data:
  external-secrets-policy.hcl: |
    # Read-only access to secrets
    path "secret/data/tradesense/*" {
      capabilities = ["read", "list"]
    }
    
    # Access to metadata
    path "secret/metadata/tradesense/*" {
      capabilities = ["read", "list"]
    }
    
    # Ability to read configuration
    path "sys/internal/ui/mounts/secret" {
      capabilities = ["read"]
    }