# App of Apps Pattern - Root Application
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/tarigelamin1997/tradesense.git
    targetRevision: HEAD
    path: k8s/argocd/applications
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - Validate=true
    - CreateNamespace=false
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
---
# ArgoCD Project for TradeSense
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: tradesense
  namespace: argocd
spec:
  description: TradeSense Trading Platform
  
  # Source repositories
  sourceRepos:
  - https://github.com/tarigelamin1997/tradesense.git
  - https://charts.bitnami.com/bitnami
  - https://kubernetes.github.io/ingress-nginx
  - https://prometheus-community.github.io/helm-charts
  
  # Destinations
  destinations:
  - namespace: tradesense
    server: https://kubernetes.default.svc
  - namespace: tradesense-staging
    server: https://kubernetes.default.svc
  - namespace: monitoring
    server: https://kubernetes.default.svc
  - namespace: ingress-nginx
    server: https://kubernetes.default.svc
  
  # Cluster resource whitelist
  clusterResourceWhitelist:
  - group: ''
    kind: Namespace
  - group: ''
    kind: ClusterRole
  - group: ''
    kind: ClusterRoleBinding
  - group: 'apiextensions.k8s.io'
    kind: CustomResourceDefinition
  
  # Namespace resource whitelist
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  
  # Roles
  roles:
  - name: admin
    policies:
    - p, proj:tradesense:admin, applications, *, tradesense/*, allow
    groups:
    - argocd-admins
  
  - name: readonly
    policies:
    - p, proj:tradesense:readonly, applications, get, tradesense/*, allow
    groups:
    - authenticated