# ArgoCD Secrets - Store these in your secret management system
apiVersion: v1
kind: Secret
metadata:
  name: argocd-secret
  namespace: argocd
type: Opaque
stringData:
  # Admin password (bcrypt hashed) - Change this!
  # Generate with: htpasswd -nbBC 10 "" YOUR_PASSWORD | tr -d ':\n' | sed 's/$2y/$2a/'
  admin.password: "$2a$10$rBxVW0OELwGOp5Zqr5f5/Oa5VwGW3hSJqHvU3Bfm1CTbuu6qrPdG."
  admin.passwordMtime: "2024-01-20T10:00:00Z"
  
  # Server secret key
  server.secretkey: "YOUR_SECRET_KEY_HERE"
  
  # GitHub webhook secret
  webhook.github.secret: "YOUR_GITHUB_WEBHOOK_SECRET"
  
  # Dex OAuth2 config
  dex.github.clientId: "YOUR_GITHUB_OAUTH_CLIENT_ID"
  dex.github.clientSecret: "YOUR_GITHUB_OAUTH_CLIENT_SECRET"
---
# Repository credentials
apiVersion: v1
kind: Secret
metadata:
  name: tradesense-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  type: git
  url: https://github.com/tarigelamin1997/tradesense.git
  # For private repos, add:
  # username: YOUR_GITHUB_USERNAME
  # password: YOUR_GITHUB_TOKEN
---
# Slack notification token
apiVersion: v1
kind: Secret
metadata:
  name: argocd-notifications-secret
  namespace: argocd
type: Opaque
stringData:
  slack-token: "YOUR_SLACK_TOKEN"