# Production overlay for Kustomize
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tradesense

bases:
  - ../../

# Production-specific resources
resources:
  - hpa-backend.yaml
  - hpa-frontend.yaml
  - pdb.yaml

# Image management for production
images:
  - name: tradesense/backend
    newTag: v1.0.0  # Use specific version tags in production
  - name: tradesense/frontend
    newTag: v1.0.0

# Config for production
configMapGenerator:
  - name: tradesense-config
    behavior: merge
    literals:
      - ENVIRONMENT=production
      - DEBUG=false
      - LOG_LEVEL=WARNING

# Production patches
patches:
  - target:
      kind: Deployment
      name: backend
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
      - op: add
        path: /spec/template/spec/affinity
        value:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - backend
              topologyKey: kubernetes.io/hostname
  - target:
      kind: Deployment
      name: frontend
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2

# Production labels
commonLabels:
  environment: production
  tier: production

# Production annotations
commonAnnotations:
  argocd.argoproj.io/sync-options: PruneLast=true